version: "3.9"

services:
  db:
    image: postgres:13
    container_name: db_app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - backend_network

  
  app:
    build: 
      context: .
    env_file:
     - .env
    container_name: fastapi_app
    ports:
     - 8000:8000
    depends_on:
     - db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
