apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scb-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scb-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "scb-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scb-app.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "scb-app.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.enableDefaultInitContainers .Values.initContainers.waitForPostgres.enabled }}
      initContainers:
        - name: wait-for-postgres
          image: {{ .Values.initContainers.waitForPostgres.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: {{ default (include "scb-app.postgresServiceHost" .) .Values.initContainers.waitForPostgres.host | quote }}
            - name: POSTGRES_PORT
              value: {{ default (printf "%v" .Values.postgres.service.port) .Values.initContainers.waitForPostgres.port | quote }}
          command:
            {{- toYaml .Values.initContainers.waitForPostgres.command | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ include "scb-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          env:
            {{- range $index, $key := .Values.env.configKeys }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "scb-app.configMapName" $ }}
                  key: {{ $key }}
            {{- end }}
            {{- range $index, $key := .Values.env.secretKeys }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "scb-app.secretName" $ }}
                  key: {{ $key }}
            {{- end }}
            {{- if .Values.env.extra }}
            {{- range .Values.env.extra }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
