{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scb-app.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scb-app.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
{{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
