apiVersion: v1
kind: Service
metadata:
  name: {{ include "scb-app.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scb-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "scb-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
