global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  # Отключаем persistence для локальной разработки
  persistence:
    enabled: false

  # Упрощаем конфигурацию
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        tls_disable = true
      }
      storage "file" {
        path = "/vault/data"
      }

ui:
  enabled: true
  service:
    enabled: true
    type: NodePort
    nodePort: 32000

ingress:
  enabled: false  # Отключаем ingress для локальной разработки