apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres..."
              until nc -zv postgres-clusterip.app.svc.cluster.local 5432; do
                sleep 1
              done
              echo "Postgres is up"
      containers:
        - name: backend
          image: backend:0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: GUNICORN_WORKERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GUNICORN_WORKERS
            - name: GUNICORN_BIND
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GUNICORN_BIND
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AUTH_SECRET_KEY
            - name: AUTH_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_ALGORITHM
            - name: AUTH_ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_ACCESS_TOKEN_EXPIRE_MINUTES
            - name: DADATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DADATA_API_KEY
          ports:
            - name: http
              containerPort: 8000
          # Переопределяем команду, чтобы НЕ запускать alembic здесь:
          command: ["sh","-c"]
          args:
            - |
              gunicorn app.main:app --workers ${GUNICORN_WORKERS} --worker-class uvicorn.workers.UvicornWorker --bind=${GUNICORN_BIND}
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"