apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  APP_ENV: "local"
  GUNICORN_WORKERS: "2"
  GUNICORN_BIND: "0.0.0.0:8000"
  POSTGRES_HOST: "postgres-0.postgres.app.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "appdb"
  AUTH_ACCESS_TOKEN_EXPIRE_MINUTES: "120"
  AUTH_ALGORITHM: "HS256"
