apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
data:
  POSTGRES_PASSWORD: ZGJwYXNzd29yZA==
  POSTGRES_USER: ZGJ1c2Vy
  DADATA_API_KEY: NjM3MDg4Mjg5ZGJmYTlhNzQxYTIwYmI2ZGU4Y2JjMDBjYzNlN2I3ZQ==
  AUTH_SECRET_KEY: MDcwa3BmNnJtZ21p
