apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.serviceName" . }}
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  selector:
{{ include "backend.selectorLabels" . | indent 4 }}
  {{- with .Values.service }}
  ports:
  {{- with .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  type: {{ .type }}
  {{- end }}
