apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
{{ include "backend.labels" . | indent 4 }}
data:
  POSTGRES_HOST: "{{ .Values.global.services.postgres }}.app.svc.cluster.local"
  POSTGRES_PORT: "5432"
  {{- range $key, $val := .Values.global.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}