apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
{{ include "backend.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.global.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
