apiVersion: v1
kind: Service
metadata:
  name: {{ include "courier-app.backend.fullname" . }}
  namespace: {{ include "courier-app.namespace" . }}
  labels:
    {{- include "courier-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "courier-app.backend.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
