apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "courier-app.fullname" . }}-config
  namespace: {{ include "courier-app.namespace" . }}
  labels:
    {{- include "courier-app.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  GUNICORN_WORKERS: {{ .Values.config.gunicorn.workers | quote }}
  GUNICORN_BIND: {{ .Values.config.gunicorn.bind | quote }}
  POSTGRES_HOST: {{ default (include "courier-app.postgres.primaryHost" .) .Values.config.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.config.postgres.port | toString | quote }}
  POSTGRES_DB: {{ .Values.config.postgres.database | quote }}
  AUTH_ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.auth.accessTokenExpireMinutes | toString | quote }}
  AUTH_ALGORITHM: {{ .Values.config.auth.algorithm | quote }}
