{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "courier-app.postgres.fullname" . }}
  namespace: {{ include "courier-app.namespace" . }}
  labels:
    {{- include "courier-app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "courier-app.postgres.headless" . }}
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "courier-app.postgres.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "courier-app.postgres.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
              name: pg
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "courier-app.fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "courier-app.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "courier-app.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: data
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: {{ include "courier-app.postgres.pvcName" . }}
{{- end }}
