apiVersion: v1
kind: Secret
metadata:
  name: {{ include "courier-app.fullname" . }}-secret
  namespace: {{ include "courier-app.namespace" . }}
  labels:
    {{- include "courier-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ required "secrets.postgres.user is required" .Values.secrets.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "secrets.postgres.password is required" .Values.secrets.postgres.password | b64enc | quote }}
  AUTH_SECRET_KEY: {{ required "secrets.auth.secretKey is required" .Values.secrets.auth.secretKey | b64enc | quote }}
  {{- if .Values.secrets.dadataApiKey }}
  DADATA_API_KEY: {{ .Values.secrets.dadataApiKey | b64enc | quote }}
  {{- end }}
