apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.configMapName" . }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
data:
  POSTGRES_HOST: {{ $.Values.global.services.postgres }}.app.svc.cluster.local
  POSTGRES_PORT: {{ .Values.service.ports.port | quote }}
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | quote }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}