apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretsName" . }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}