 ---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
{{ include "postgres.labels" . | indent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  {{- with .ports }}
  ports:
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}
  {{- end }}
  selector:
{{ include "postgres.selectorLabels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-clusterip
spec:
  selector:
{{ include "postgres.selectorLabels" . | indent 4 }}
  {{- with .Values.service.ports }}
  ports:
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}