apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes | quote }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
  selector:
    matchLabels:
{{ include "postgres.selectorLabels" . | indent 6 }}

