"""new triggers

Revision ID: 0ec7dbd4b1e7
Revises: 5815ec61af20
Create Date: 2024-09-15 19:00:31.197377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec7dbd4b1e7'
down_revision: Union[str, None] = '5815ec61af20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE FUNCTION add_application_status() 
    RETURNS TRIGGER AS $$
    BEGIN
    INSERT INTO application_status_current(application_id, status, load_date)
    VALUES (NEW.id, 'New', NOW());
    RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    
    op.execute("""
    CREATE TRIGGER trigger_add_application_status
    AFTER INSERT ON application
    FOR EACH ROW
    EXECUTE FUNCTION add_application_status();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
