"""added application status models

Revision ID: 5815ec61af20
Revises: 68cac587239b
Create Date: 2024-09-15 14:29:32.306710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5815ec61af20'
down_revision: Union[str, None] = '68cac587239b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_status_current',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('application_status_history',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('load_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'load_date')
    )
    op.add_column('application', sa.Column('ship_date', sa.Date(), nullable=False))
    op.add_column('application', sa.Column('ship_time', sa.Time(), nullable=False))
    op.add_column('application', sa.Column('load_date', sa.DateTime(), nullable=True))
    op.drop_column('application', 'ship_datetime')
    
    op.execute("""
    CREATE OR REPLACE FUNCTION insert_status_history() 
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO application_status_history (application_id, status, load_date)
        VALUES (NEW.application_id, NEW.status, NOW());
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trigger_insert_status_history
    AFTER UPDATE or INSERT ON application_status_current
    FOR EACH ROW
    EXECUTE FUNCTION insert_status_history();
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('ship_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('application', 'load_date')
    op.drop_column('application', 'ship_time')
    op.drop_column('application', 'ship_date')
    op.drop_table('applicateion_status_history')
    op.drop_table('applicateion_status_current')
    # ### end Alembic commands ###
