"""added application and package type models

Revision ID: 68cac587239b
Revises: 18b2ed30df3a
Create Date: 2024-09-14 19:43:04.854466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cac587239b'
down_revision: Union[str, None] = '18b2ed30df3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('ship_datetime', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('package_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_type_id'], ['package_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
    INSERT INTO package_type (id, type) VALUES
    (1, 'Письмо'),
    (2, 'Бандероль'),
    (3, 'Габаритный груз');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('package_type')
    # ### end Alembic commands ###
