"""warehouse model

Revision ID: d08f0d116a3b
Revises: 
Create Date: 2024-09-13 01:23:40.576533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08f0d116a3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('geo_lat', sa.Float(), nullable=False),
    sa.Column('geo_lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
    INSERT INTO warehouse (id, city, address, geo_lat, geo_lon) VALUES
    (1, 'Казань', 'г Казань, ул Островского, зд 98', 55.77934, 49.132362),
    (2, 'Набережные Челны', 'Респ Татарстан, г Набережные Челны, Московский пр-кт, д 161', 55.744485, 52.43098),
    (3, 'Нижнекамск', 'Респ Татарстан, г Нижнекамск, пл Им Н.В.Лемаева, зд 2', 55.63752, 51.81805),
    (4, 'Альметьевск', 'Респ Татарстан, г Альметьевск, ул Ленина, д 100', 54.89938, 52.274017),
    (5, 'Зеленодольск', 'Респ Татарстан, г Зеленодольск, ул Королева, д 1', 55.853573, 48.56483);
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    # ### end Alembic commands ###
