secret:
  create: true
  stringData:
    POSTGRES_USER: ref+vault://kv/data/app/backend#data.POSTGRES_USER
    POSTGRES_PASSWORD: ref+vault://kv/data/app/backend#data.POSTGRES_PASSWORD
    AUTH_SECRET_KEY: ref+vault://kv/data/app/backend#data.AUTH_SECRET_KEY
    DADATA_API_KEY: ref+vault://kv/data/app/backend#data.DADATA_API_KEY

postgres:
  env:
    secretName: app-secret
