postgres:
  secret:
    POSTGRES_PASS: ref+vault://secrets/db#/password
    POSTGRES_USER: ref+vault://secrets/db#/username
    POSTGRES_DB: ref+vault://secrets/db#/db
    DADATA_API_KEY: ref+vault://secrets/db#/dadata_api_key
    AUTH_SECRET_KEY: ref+vault://secrets/db#/auth_secret_key